(function(){
'use strict';
const $=id=>document.getElementById(id),openMidi=[64,59,55,50,45,40],names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'],persian=['دو','دو دیز','ر','ر دیز','می','فا','فا دیز','سل','سل دیز','لا','لا دیز','سی'],ord=['اول','دوم','سوم','چهارم','پنجم','ششم'];
const fa=n=>Number(n).toLocaleString('fa-IR');let currentFret=0,enabled=false,muted=false,rotation=false,demoTimers=[],demoPlaying=false,toastTimer;
function noteAt(s,f){const midi=openMidi[s]+f;return{midi,note:names[midi%12]+(Math.floor(midi/12)-1),frequency:440*Math.pow(2,(midi-69)/12)};}
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
function setReady(){if(enabled)return;enabled=true;window.guitarHoverEnabled=true;$('start-audio').querySelector('span').textContent='ساز در دستان توست';$('start-audio').querySelector('svg').innerHTML='<path d="m5 12 4 4L20 5" fill="none" stroke="currentColor" stroke-width="2"/>';}
function updateStatus(source){$('audio-status').innerHTML='<i></i> '+(muted?'صدا خاموش است':!enabled?'برای فعال‌شدن صدا، یک‌بار کلیک کن':source==='sample'?'صدای سمپل گیتار کلاسیک · کوک استاندارد':'صدای مدل‌سازی‌شدهٔ گیتار · کوک استاندارد');}
async function activate(){try{await window.GuitarAudio.unlock();setReady();return true;}catch(error){console.error('Audio activation failed',error);toast('صدا فعال نشد؛ دوباره روی «شروع نواختن» بزن.');return false;}}
async function play(s,f,velocity=.8){if(!Number.isInteger(s)||s<0||s>5)return;const n=noteAt(s,f);$('note-name').textContent=n.note;$('frequency').textContent=n.frequency.toFixed(2)+' Hz';$('note-info').textContent=persian[n.midi%12]+' · سیم '+ord[s]+' · '+(f?'فرت '+fa(f):'آزاد');$('note-dot').classList.remove('pulse');void $('note-dot').offsetWidth;$('note-dot').classList.add('pulse');window.GuitarScene?.pluck(s,f);const b=document.querySelector('[data-string="'+s+'"]');if(b){b.classList.add('playing');setTimeout(()=>b.classList.remove('playing'),220);}try{const result=await window.GuitarAudio.play(s,f,velocity);setReady();updateStatus(result.source);}catch(error){console.error('Guitar note failed',error);toast('برای فعال‌کردن صدا، دکمهٔ شروع نواختن را لمس کن.');}}
window.addEventListener('guitar-pluck',e=>{if(demoPlaying)stopDemo();play(e.detail.string,e.detail.fret,e.detail.velocity);});
window.addEventListener('guitar-hover',e=>{const el=$('pointer-note');if(!e.detail||rotation){el.classList.remove('visible');return;}const h=e.detail;el.textContent=noteAt(h.string,h.fret).note+' · '+(h.fret?'F'+h.fret:'Open');el.style.left=Math.min(h.x+15,window.innerWidth-100)+'px';el.style.top=Math.max(7,h.y-46)+'px';el.classList.add('visible');});
window.addEventListener('guitar-audio-state',e=>updateStatus(e.detail.source));window.addEventListener('samples-ready',()=>{if(enabled)updateStatus('sample');});
$('start-audio').onclick=async()=>{if(await activate()){if(muted){muted=false;window.GuitarAudio.mute(false);$('mute').setAttribute('aria-pressed','false');$('mute').setAttribute('aria-label','بی‌صدا کردن');$('mute').style.opacity='1';}play(5,0,.6);toast('روی سیم‌ها حرکت کن یا یک فرت را لمس کن؛ هر نقطه، نت خودش را دارد.');}};
function stopDemo(){for(const t of demoTimers)clearTimeout(t);demoTimers=[];demoPlaying=false;$('demo').classList.remove('active');$('demo').querySelector('span').textContent='یک جرعه موسیقی';$('demo').setAttribute('aria-label','شنیدن یک آرپژ کوتاه');}
$('demo').onclick=async()=>{if(demoPlaying){stopDemo();window.GuitarAudio.stop();return;}if(!await activate())return;demoPlaying=true;$('demo').classList.add('active');$('demo').querySelector('span').textContent='توقف موسیقی';$('demo').setAttribute('aria-label','توقف موسیقی');const chords=[[0,1,2,2,0,-1],[0,0,0,2,2,0],[1,1,2,3,-1,-1],[0,0,1,2,2,0]],pattern=[4,2,1,0,1,2,0,1];let time=0;for(let cycle=0;cycle<2;cycle++)for(let c of chords)for(let s0 of pattern){let s=s0;if(c[s]<0)s=3;const f=c[s];demoTimers.push(setTimeout(()=>play(s,f,.55+(s>3?.12:0)),time));time+=350;}demoTimers.push(setTimeout(stopDemo,time+1600));};
$('volume').oninput=e=>{const v=Number(e.target.value)/100;window.GuitarAudio.setVolume(v);};window.GuitarAudio.setVolume(.65);
$('mute').onclick=()=>{muted=!muted;window.GuitarAudio.mute(muted);$('mute').setAttribute('aria-pressed',String(muted));$('mute').setAttribute('aria-label',muted?'روشن کردن صدا':'بی‌صدا کردن');$('mute').style.opacity=muted?'.4':'1';updateStatus(window.GuitarAudio.getStatus().source);};
$('view').onclick=()=>{if(!window.GuitarScene){toast('نمای سه‌بعدی هنوز آماده نیست.');return;}rotation=!rotation;window.GuitarScene.setRotate(rotation);$('view').setAttribute('aria-pressed',String(rotation));$('pointer-note').classList.remove('visible');toast(rotation?'برای دیدن جزئیات، گیتار را با کشیدن بچرخان. دوباره روی مکعب بزن تا بنوازی.':'حالت نواختن فعال شد.');};
$('reset').onclick=()=>{window.GuitarScene?.reset();rotation=false;$('view').setAttribute('aria-pressed','false');toast('گیتار به نمای اصلی برگشت.');};
for(let f=0;f<=19;f++){const opt=document.createElement('option');opt.value=f;opt.textContent=f?fa(f):'آزاد';$('fret-select').appendChild(opt);}
function renderKeys(){const box=$('string-keys');box.replaceChildren();for(let s=0;s<6;s++){const b=document.createElement('button');b.className='string-key';b.dataset.string=s;const note=noteAt(s,currentFret).note;b.innerHTML='<b>'+note+'</b><small>سیم '+fa(s+1)+'</small>';b.setAttribute('aria-label','سیم '+ord[s]+'، '+(currentFret?'فرت '+fa(currentFret):'آزاد')+'، '+note);b.onclick=()=>{stopDemo();play(s,currentFret);};box.appendChild(b);}}
renderKeys();$('fret-select').onchange=e=>{currentFret=Number(e.target.value);renderKeys();};$('fret-toggle').setAttribute('aria-expanded','false');$('fret-toggle').onclick=()=>{const panel=$('fret-panel');panel.hidden=!panel.hidden;$('fret-toggle').setAttribute('aria-expanded',String(!panel.hidden));$('fret-toggle').innerHTML=(panel.hidden?'نمایش':'بستن')+' نت‌ها و فرت‌ها <span>'+(panel.hidden?'＋':'−')+'</span>';};
window.addEventListener('keydown',e=>{if(e.repeat||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)||$('info-dialog').open)return;const normalized=e.key.replace(/[۱-۶]/g,c=>'۱۲۳۴۵۶'.indexOf(c)+1);if(/^[1-6]$/.test(normalized)){e.preventDefault();stopDemo();play(Number(normalized)-1,currentFret);}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();currentFret=Math.max(0,Math.min(19,currentFret+(e.key==='ArrowRight'?1:-1)));$('fret-select').value=currentFret;renderKeys();toast(currentFret?'فرت '+fa(currentFret):'سیم آزاد');}});
const content={guide:'<p class="dialog-kicker">A LITTLE GUIDE TO YOUR FIRST NOTE</p><h2>موسیقی، به سادگی یک لمس</h2><ul><li>ابتدا «شروع نواختن» را بزن تا مرورگر اجازهٔ پخش صدا بدهد.</li><li>روی قسمت آزاد سیم‌ها، نت آزاد پخش می‌شود. روی دسته، هر خانهٔ بین دو فرت، نت مخصوص همان سیم را دارد.</li><li>بعد از فعال‌شدن صدا، ماوس را روی سیم‌ها بکش. در موبایل، لمس کن یا انگشتت را روی سیم‌ها حرکت بده.</li><li>برای انتخاب دقیق‌تر، «نمایش نت‌ها و فرت‌ها» را باز کن. ۶ سیم و فرت‌های صفر تا ۱۹ قابل نواختن‌اند.</li><li>دکمهٔ مکعب، حالت چرخش گیتار را فعال می‌کند؛ دکمهٔ کنار آن، نمای اصلی را برمی‌گرداند.</li><li>کلیدهای ۱ تا ۶، سیم‌ها را می‌نوازند. جهت چپ و راست، فرت را تغییر می‌دهند.</li></ul><p>کوک استاندارد: E2 · A2 · D3 · G3 · B3 · E4. یک نت می‌تواند روی چند سیم تکرار شود؛ جنس صدای سیم و محل نواختن متفاوت است.</p><p>صدا از نمونهٔ گیتار کلاسیک FluidR3 پخش می‌شود؛ اگر نمونه‌ها در دسترس نباشند، مدل‌سازی سیم جایگزین خواهد شد.</p>',about:'<p class="dialog-kicker">HASHEM SHAKIBA MUSIC ATELIER</p><h2>آموزشگاه موسیقی<br>استاد هاشم شکیبا</h2><p>اینجا، شروع یک رابطهٔ عاشقانه با موسیقی است. پیش از هر درس، چند لحظه به صدای یک سیم گوش بده؛ شاید اولین نتِ مسیر تو همین باشد.</p><p>این صفحه، فضای تعاملی آموزشگاه است. اطلاعات دوره‌ها، نشانی و راه‌های ثبت‌نام پس از دریافت اطلاعات تأییدشدهٔ آموزشگاه اضافه می‌شوند.</p><p class="dialog-kicker">SOUND: FLUIDR3 GM / MIDI.JS SOUNDFONTS<br>3D EXPERIENCE: THREE.JS</p>'};
for(const b of document.querySelectorAll('[data-modal]'))b.onclick=()=>{$('dialog-content').innerHTML=content[b.dataset.modal];$('info-dialog').showModal();};document.querySelector('.dialog-close').onclick=()=>$('info-dialog').close();$('info-dialog').addEventListener('click',e=>{if(e.target===$('info-dialog')){const r=$('info-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('info-dialog').close();}});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopDemo();window.GuitarAudio.stop();}});
window.ShakibaApp={play,noteAt,getState:()=>({enabled,muted,currentFret,demoPlaying})};
})();
