/* Hand-built classical guitar. Dimensions and hit testing share one scale-length model. */
(function(){
'use strict';
const host=document.getElementById('guitar-stage'),loading=document.getElementById('scene-loading');
if(!window.THREE){loading.classList.add('error');loading.innerHTML='نمای سه‌بعدی بارگذاری نشد. اتصال اینترنت را بررسی کنید.<br>برای نواختن، از «نمایش نت‌ها و فرت‌ها» استفاده کنید.';return;}
const T=window.THREE;
let renderer;
try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});}catch(err){console.error(err);loading.classList.add('error');loading.textContent='مرورگر شما امکان نمایش سه‌بعدی را ندارد. از پنل نت‌ها برای نواختن استفاده کنید.';return;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor(0,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.VSMShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.24;host.appendChild(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(33,1,.1,100),guitar=new T.Group();scene.add(guitar);
const ambient=new T.HemisphereLight(0xfff5e6,0x6c4831,2.3);scene.add(ambient);
const key=new T.DirectionalLight(0xfff1da,3.2);key.position.set(-4,7,12);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.1,far:35});key.shadow.normalBias=.035;key.shadow.bias=-.0002;key.shadow.radius=4;key.shadow.blurSamples=8;scene.add(key);
const fill=new T.DirectionalLight(0xe7efff,1.3);fill.position.set(5,-2,6);scene.add(fill);const rim=new T.DirectionalLight(0xffce8c,1.6);rim.position.set(2,8,-1);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(50,50),new T.ShadowMaterial({opacity:.09}));floor.position.z=-1.4;floor.receiveShadow=true;scene.add(floor);
let seed=7281;function rand(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646;}
function woodTexture(dark=false){const c=document.createElement('canvas');c.width=512;c.height=1024;const ctx=c.getContext('2d');ctx.fillStyle=dark?'#4e2515':'#c18a49';ctx.fillRect(0,0,512,1024);for(let x=0;x<512;x++){const v=rand();ctx.strokeStyle=dark?`rgba(14,3,0,${.06+v*.23})`:`rgba(87,39,6,${.025+v*.12})`;ctx.lineWidth=.3+rand()*1.1;ctx.beginPath();for(let y=0;y<=1024;y+=8){const xx=x+Math.sin(y*.007+x*.4)*(dark?5:1.1)+Math.sin(y*.02+x)*.45;if(y===0)ctx.moveTo(xx,y);else ctx.lineTo(xx,y);}ctx.stroke();if(x%4===0){ctx.fillStyle=dark?'#d3975820':'#ffe3a536';ctx.fillRect(x,0,.6,1024);}}for(let i=0;i<13000;i++){ctx.fillStyle=rand()>.5?'#ffffff09':'#2d0f0009';ctx.fillRect(rand()*512,rand()*1024,1,1);}const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(.23,.13);return tex;}
const spruce=woodTexture(),rosewood=woodTexture(true);
function mat(color,roughness=.4,metalness=0){return new T.MeshStandardMaterial({color,roughness,metalness});}
const topMat=new T.MeshPhysicalMaterial({map:spruce,color:0xf4cc89,roughness:.33,clearcoat:.7,clearcoatRoughness:.28});const sideMat=new T.MeshPhysicalMaterial({map:rosewood,color:0x9b6241,roughness:.3,clearcoat:.7});const darkMat=new T.MeshStandardMaterial({map:rosewood,color:0x382316,roughness:.68});const ivory=mat(0xeee0bc,.33),black=mat(0x201b17,.6),gold=mat(0xc7a570,.24,.8),silver=mat(0xcfc6ad,.24,.85);
function add(geo,material,x=0,y=0,z=0,parent=guitar){const mesh=new T.Mesh(geo,material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function box(w,h,d,material,x,y,z,parent){return add(new T.BoxGeometry(w,h,d),material,x,y,z,parent);}
function tube(a,b,r,material,parent=guitar){const v1=new T.Vector3(...a),v2=new T.Vector3(...b),delta=v2.clone().sub(v1);const m=add(new T.CylinderGeometry(r,r,delta.length(),10),material,0,0,0,parent);m.position.copy(v1).add(v2).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());return m;}
function outline(hole=false){const s=new T.Shape();s.moveTo(0,2.03);s.bezierCurveTo(.8,2.03,1.48,1.83,1.52,1.14);s.bezierCurveTo(1.58,.61,.98,.28,1.1,-.19);s.bezierCurveTo(1.19,-.67,1.94,-.87,1.93,-1.56);s.bezierCurveTo(1.94,-2.44,.92,-2.84,0,-2.84);s.bezierCurveTo(-.92,-2.84,-1.94,-2.44,-1.93,-1.56);s.bezierCurveTo(-1.94,-.87,-1.19,-.67,-1.1,-.19);s.bezierCurveTo(-.98,.28,-1.58,.61,-1.52,1.14);s.bezierCurveTo(-1.48,1.83,-.8,2.03,0,2.03);if(hole){const h=new T.Path();h.absarc(0,.23,.64,0,Math.PI*2,true);s.holes.push(h);}return s;}
function extrude(shape,depth,material,z,bevel=.015){return add(new T.ExtrudeGeometry(shape,{depth,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:bevel,bevelThickness:bevel,curveSegments:64}),material,0,0,z);}
extrude(outline(),.035,ivory,-.44,.025);extrude(outline(true),.65,sideMat,-.41,.02);extrude(outline(true),.034,ivory,.255,.022);const top=extrude(outline(true),.046,topMat,.30,.014);top.scale.set(.987,.99,1);
const edging=new T.LineLoop(new T.BufferGeometry().setFromPoints(outline().getPoints(220).map(p=>new T.Vector3(p.x*.978,p.y*.981,.368))),new T.LineBasicMaterial({color:0x714921}));guitar.add(edging);
add(new T.CircleGeometry(.644,80),mat(0x130d09,.98),0,.23,-.36);
// Inlaid rosette, with individual repeating mosaic tiles.
function ring(inner,outer,material,z=.37){return add(new T.RingGeometry(inner,outer,120),material,0,.23,z);}
ring(.648,.9,mat(0x422c1b,.52));ring(.667,.685,ivory);ring(.71,.725,ivory);ring(.835,.85,ivory);ring(.883,.903,ivory);ring(.753,.813,mat(0xac6d39));for(let i=0;i<88;i++){const a=i*Math.PI*2/88;const tile=box(.021,.054,.005,i%2?ivory:darkMat,Math.cos(a)*.783,.23+Math.sin(a)*.783,.376);tile.rotation.z=a+.7;}
// Heel, rosewood neck, gently tapered ebony fingerboard.
const heel=add(new T.SphereGeometry(.39,28,16),sideMat,0,1.83,-.10);heel.scale.set(.96,1.65,.82);
box(.58,4.7,.26,sideMat,0,3.82,.075);const boardShape=new T.Shape();boardShape.moveTo(-.365,.85);boardShape.lineTo(.365,.85);boardShape.lineTo(.279,6.18);boardShape.lineTo(-.279,6.18);boardShape.closePath();extrude(boardShape,.085,darkMat,.325,.014);
const nutY=6.18,saddleY=-1.78,scaleLength=nutY-saddleY;
const fretY=[nutY];for(let f=1;f<=19;f++){const y=nutY-scaleLength*(1-Math.pow(2,-f/12));fretY.push(y);const w=.56+(nutY-y)/5.33*.174;tube([-w/2,y,.439],[w/2,y,.439],.009,silver);}
box(.595,.074,.102,ivory,0,nutY,.412);for(let f of[3,5,7,9,12,15,17]){const y=(fretY[f-1]+fretY[f])/2;const width=.56+(nutY-y)/5.33*.174;for(let offset of(f===12?[-.08,.08]:[0])){const dot=add(new T.SphereGeometry(.016,10,8),ivory,-width/2-.008,y+offset,.405);dot.scale.set(.5,1,1);}}
// Slotted classical headstock with inlaid crest and full tuning machinery.
const headShape=new T.Shape();headShape.moveTo(-.28,6.18);headShape.lineTo(-.405,6.52);headShape.lineTo(-.43,7.68);headShape.quadraticCurveTo(-.34,7.86,-.19,7.8);headShape.quadraticCurveTo(0,7.98,.19,7.8);headShape.quadraticCurveTo(.34,7.86,.43,7.68);headShape.lineTo(.405,6.52);headShape.lineTo(.28,6.18);headShape.closePath();for(let x of[-.225,.225]){const h=new T.Path();h.moveTo(x-.079,6.62);h.lineTo(x-.079,7.54);h.quadraticCurveTo(x,7.65,x+.079,7.54);h.lineTo(x+.079,6.62);h.quadraticCurveTo(x,6.53,x-.079,6.62);headShape.holes.push(h);}
extrude(headShape,.19,sideMat,.16,.028);const face=extrude(headShape,.023,darkMat,.368,.007);for(let side of[-1,1]){box(.047,1.02,.13,gold,side*.425,7.12,.225);for(let j=0;j<3;j++){let y=6.76+j*.33;tube([side*.11,y,.275],[side*.48,y,.275],.042,ivory);const cog=add(new T.CylinderGeometry(.08,.08,.04,16),gold,side*.465,y,.23);cog.rotation.z=Math.PI/2;tube([side*.46,y,.23],[side*.64,y,.23],.019,silver);const peg=add(new T.SphereGeometry(.10,20,14),ivory,side*.66,y,.23);peg.scale.set(.54,1.23,.78);const screw=add(new T.SphereGeometry(.022,10,8),silver,side*.444,y+.105,.30);}}
const crest=add(new T.CircleGeometry(.077,4),ivory,0,7.62,.402);crest.rotation.z=Math.PI/4;crest.scale.set(.75,1.4,1);
// Carved bridge, saddle, tie block, string knots.
box(1.22,.35,.103,darkMat,0,-1.85,.398);box(.73,.27,.128,darkMat,0,-1.85,.405);box(.75,.045,.065,ivory,0,saddleY,.482);box(.77,.06,.04,ivory,0,-1.986,.471);
const strings=[],vibes=[];for(let i=0;i<6;i++){const xN=(i-2.5)*.098,xB=(i-2.5)*.136;const material=mat(i<3?0xddd3b6:0xcba675,i<3?.3:.38,i<3?.35:.78);const radius=.0032+i*.0011;const a=[xB,-1.98,.52],b=[xN,nutY,.493];const mesh=tube(a,b,radius,material);mesh.castShadow=false;strings.push({i,a,b,xN,xB,mesh});tube([xB,-2.02,.48],[xB,saddleY,.535],radius,material);const side=i<3?-1:1,j=i<3?i:5-i;tube([xN,nutY,.493],[side*.22,6.76+j*.33,.306],radius,material);const points=new Float32Array(65*3);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(points,3));const line=new T.Line(geo,new T.LineBasicMaterial({color:0xffd890,transparent:true,opacity:0}));line.frustumCulled=false;guitar.add(line);vibes.push({line,start:-10,fret:0});}
// Invisible generous hit area is transformed with the model.
const hitbox=box(.84,8.27,.01,new T.MeshBasicMaterial({visible:false}),0,2.15,.554);hitbox.castShadow=false;
const marker=add(new T.RingGeometry(.042,.056,40),new T.MeshBasicMaterial({color:0xffde98,transparent:true,opacity:.95,depthTest:false}),0,0,.567);marker.visible=false;marker.renderOrder=5;
let aspect=1,rotateMode=false,dragging=false,lastX=0,lastY=0,pointerDown=false,lastPlayed='',currentHover=null;const base={x:-.16,y:-.25,z:-1.04};let targetX=base.x,targetY=base.y,targetZ=base.z;
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);aspect=w/h;camera.aspect=aspect;const spanW=10.9,spanH=7.5;const distance=Math.max(spanH/(2*Math.tan(T.MathUtils.degToRad(16.5))),spanW/(2*Math.tan(T.MathUtils.degToRad(16.5))*aspect));camera.position.set(0,0,distance);camera.updateProjectionMatrix();guitar.position.set(-1.75,-1.06,0);}
new ResizeObserver(resize).observe(host);resize();
const ray=new T.Raycaster(),pointer=new T.Vector2();function hit(event){const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObject(hitbox);if(!hits.length)return null;const p=guitar.worldToLocal(hits[0].point.clone());let f=0;if(p.y>fretY[19]&&p.y<nutY){for(let n=1;n<=19;n++){if(p.y>=fretY[n]){f=n;break;}}}const mix=T.MathUtils.clamp((p.y-saddleY)/scaleLength,0,1);const step=.136*(1-mix)+.098*mix;const i=T.MathUtils.clamp(Math.round(p.x/step+2.5),0,5);return{string:i,fret:f,p};}
function dispatchNote(h,e,force=false){const id=h.string+':'+h.fret;if(!force&&id===lastPlayed)return;lastPlayed=id;window.dispatchEvent(new CustomEvent('guitar-pluck',{detail:{string:h.string,fret:h.fret,velocity:force?.85:.66}}));}
renderer.domElement.addEventListener('pointerdown',e=>{pointerDown=true;lastPlayed='';lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);if(rotateMode){dragging=true;return;}window.GuitarAudio?.unlock().catch(console.error);const h=hit(e);if(h)dispatchNote(h,e,true);});
renderer.domElement.addEventListener('pointermove',e=>{if(dragging){targetY+=(e.clientX-lastX)*.007;targetX+=(e.clientY-lastY)*.007;targetX=T.MathUtils.clamp(targetX,-1.1,1.1);lastX=e.clientX;lastY=e.clientY;return;}if(rotateMode)return;const h=hit(e);currentHover=h;renderer.domElement.style.cursor=h?'crosshair':'default';window.dispatchEvent(new CustomEvent('guitar-hover',{detail:h?{string:h.string,fret:h.fret,x:e.clientX,y:e.clientY}:null}));marker.visible=!!h;if(h){const mix=T.MathUtils.clamp((h.p.y-saddleY)/scaleLength,0,1);marker.position.set((h.string-2.5)*(.136*(1-mix)+.098*mix),h.p.y,.567);if(pointerDown||window.guitarHoverEnabled)dispatchNote(h,e); }else lastPlayed='';});
function end(){pointerDown=false;dragging=false;lastPlayed='';}renderer.domElement.addEventListener('pointerup',end);renderer.domElement.addEventListener('pointercancel',end);renderer.domElement.addEventListener('pointerleave',()=>{if(!pointerDown){end();marker.visible=false;window.dispatchEvent(new CustomEvent('guitar-hover',{detail:null}));}});
const clock=new T.Clock(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function animate(){requestAnimationFrame(animate);if(document.hidden)return;const time=clock.getElapsedTime();guitar.rotation.x+=(targetX-guitar.rotation.x)*.12;guitar.rotation.y+=(targetY-guitar.rotation.y)*.12;guitar.rotation.z+=(targetZ-guitar.rotation.z)*.12;guitar.position.y=-1.06+(reduced||pointerDown||currentHover?0:Math.sin(time*.6)*.025);for(let i=0;i<6;i++){const v=vibes[i],elapsed=time-v.start;if(elapsed>2.8){v.line.material.opacity=0;continue;}const s=strings[i],amplitude=Math.exp(-elapsed*2.8)*.022;v.line.material.opacity=Math.exp(-elapsed*1.5)*.85;const attr=v.line.geometry.attributes.position;const yEnd=v.fret?fretY[v.fret]:nutY;for(let n=0;n<=64;n++){const t=n/64,y=saddleY+(yEnd-saddleY)*t,m=(y-saddleY)/scaleLength;attr.setXYZ(n,s.xB+(s.xN-s.xB)*m+Math.sin(t*Math.PI)*Math.sin(time*65)*amplitude,y,.542+Math.sin(t*Math.PI*2)*amplitude*.4);}attr.needsUpdate=true;}renderer.render(scene,camera);}
guitar.rotation.set(base.x,base.y,base.z);animate();loading.remove();
window.GuitarScene={pluck(i,f){if(!vibes[i])return;vibes[i].start=clock.getElapsedTime();vibes[i].fret=f;},setRotate(v){rotateMode=v;marker.visible=false;renderer.domElement.style.cursor=v?'grab':'default';return rotateMode;},reset(){targetX=base.x;targetY=base.y;targetZ=base.z;rotateMode=false;},getFretY(f){return fretY[f];},projectNote(i,f){guitar.updateMatrixWorld(true);const y=f?(fretY[f]+fretY[f-1])/2:0;const m=(y-saddleY)/scaleLength;const p=guitar.localToWorld(new T.Vector3((i-2.5)*(.136*(1-m)+.098*m),y,.56)).project(camera);const r=renderer.domElement.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};},getInfo(){return{strings:6,frets:19,webgl:true,meshCount:guitar.children.length};}};
})();
